name: cogni
channels:
    - defaults
    - tstenner
dependencies:
    - python<3.7
    - pip
    - numpy
    - scipy>1.0.0
    - matplotlib
    - pyqt>=5
    - pandas
    - scikit-learn
    - h5py
    - sympy
    - numba
    - pytest
    - pytest-cov
    - flake8
    - pillow
    - cython
    - pip:
        - git+https://github.com/pyqtgraph/pyqtgraph.git@develop
        - pylsl
        - nibabel
        - mne==0.16
        - typing
        - expyriment
        - PyOpenGL
        - PyOpenGL_accelerate
        - pytest-sugar
        - tables
        - vispy
        - codecov

